# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171022_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='is_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
