# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171022_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Clientes', 'verbose_name_plural': 'Clientes'},
        ),
    ]
