# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171023_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['-id'], 'verbose_name': 'Clientes', 'verbose_name_plural': 'Clientes'},
        ),
    ]
