# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=30)),
                ('existencia', models.IntegerField()),
                ('is_active', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_financiamiento', models.CharField(max_length=150, verbose_name='% tasa')),
                ('porcentaje_enganche', models.CharField(max_length=3)),
                ('placo_maximo', models.IntegerField()),
                ('is_active', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='articulos',
            name='configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Configuracion'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
