# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
