# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20171022_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='configuracion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Configuracion'),
            preserve_default=False,
        ),
    ]
