# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_articulos_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
