# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20171023_2108'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulos', '0004_auto_20171023_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=13)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.DateTimeField(blank=True, default=True, null=True)),
                ('origin', models.IntegerField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Clientes')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ventas',
                'verbose_name_plural': 'Ventas',
            },
            bases=(save_the_change.mixins.SaveTheChange, models.Model),
        ),
    ]
