# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20171025_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='articulo',
        ),
    ]
