# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_auto_20171023_2130'),
        ('ventas', '0003_remove_ventas_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulos'),
            preserve_default=False,
        ),
    ]
