# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_auto_20171023_2130'),
        ('ventas', '0004_ventas_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='articulo',
        ),
        migrations.AddField(
            model_name='ventas',
            name='articulo',
            field=models.ManyToManyField(to='articulos.Articulos'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='is_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
