# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20171025_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='total',
            new_name='abono',
        ),
        migrations.AddField(
            model_name='ventas',
            name='ahorro',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='plazo',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='total_a_pagar',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
