# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20171026_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['-id'], 'verbose_name': 'Ventas', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='ventas',
            name='cantidad',
            field=models.CharField(default='', max_length=133),
            preserve_default=False,
        ),
    ]
